name: Update translations
on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.TRANSLATIONS_UPDATE }}
        
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Install dependencies
        run: sudo apt-get install -y gettext

      - name: Run Maven
        run: mvn -Pupdate-translations validate

      - name: Check changes
        id: check-changes
        continue-on-error: true
        # check if anything except "POT creation date" has changed
        run: git diff --numstat i18n/keys.pot |  awk '{ if($1 == 1 && $2 == 1) { exit 1 } else exit 0 }'

      - name: Commit changes
        if: steps.check-changes.outcome == 'success' && steps.check-changes.conclusion == 'success'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: PhoenicisBot
          author_email: git@phoenicis.org
          message: 'Update translations'
          add: '*.pot'
